// Actions for use in useApplicationData
export const ActionTypes = {
  SET_PHOTOS: 'SET_PHOTOS',
  SET_TOPICS: 'SET_TOPICS',
  SET_ERROR: 'SET_ERROR',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  SET_PHOTOS_BY_TOPIC: 'SET_PHOTOS_BY_TOPIC',
};